version: '3.8'
services:
  postgres-db-prod:
    image: postgres
    environment:
      - POSTGRES_PASSWORD= glop2425
      - POSTGRES_USER= prod_user
      - POSTGRES_DB= prod_db
    ports:
      - "5433:5432"  # PostgreSQL sera accessible via l'IP publique de la VMDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user -d prod_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - production

  postgres-db-dev:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=glop2425
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=db_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev_user -d db_dev" ]
      interval: 10s
      timeout: 5s
      retries: 5
