name: CI/CD Pipeline Microservice Gestion des utilisateurs

on:
  push:
    branches:
      - feature/*
    paths:
      - 'GestionDesUtilisateursService/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'GestionDesUtilisateursService/**'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK for compilation
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Compile the microservice
      - name: Compile Microservice Gestion des utilisateurs
        working-directory: ./GestionDesUtilisateursService
        run: |
          mvn clean compile
          echo "Compilation successful"

  build-and-test:
    runs-on: ubuntu-latest
    needs: compile # Ensure this job runs after the compile job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: echo "Environment variables are set."
        
      - name: Debug Environment Variables
        run: echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" && echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}"

      # Set up JDK for backend tests
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Run JUnit tests for backend
      - name: Run Backend JUnit Tests
        working-directory: ./GestionDesUtilisateursService
        run: |
          mvn install
          mvn test

